spring:
  cloud:
    stream:
      function:
        definition: producer
      bindings:
        output:
          destination: test
          contentType: application/json
      kafka:
        binder:
          brokers:
            - localhost:9092